
// This file has been generated by the GUI designer. Do not modify.
namespace GFCDock
{
	internal partial class DockPane
	{
		private global::Gtk.VBox vbox;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GFCDock.DockPane
			global::Stetic.BinContainer.Attach (this);
			this.Name = "GFCDock.DockPane";
			// Container child GFCDock.DockPane.Gtk.Container+ContainerChild
			this.vbox = new global::Gtk.VBox ();
			this.vbox.Name = "vbox";
			this.Add (this.vbox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
		}
	}
}
