
// This file has been generated by the GUI designer. Do not modify.
namespace GFCDock
{
	internal partial class DockAutoHide
	{
		private global::Gtk.EventBox eventbox;

		private global::Gtk.Fixed fixedpanel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GFCDock.DockAutoHide
			global::Stetic.BinContainer.Attach (this);
			this.Name = "GFCDock.DockAutoHide";
			// Container child GFCDock.DockAutoHide.Gtk.Container+ContainerChild
			this.eventbox = new global::Gtk.EventBox ();
			this.eventbox.Events = ((global::Gdk.EventMask)(12292));
			this.eventbox.Name = "eventbox";
			this.eventbox.AboveChild = true;
			this.eventbox.VisibleWindow = false;
			// Container child eventbox.Gtk.Container+ContainerChild
			this.fixedpanel = new global::Gtk.Fixed ();
			this.fixedpanel.Name = "fixedpanel";
			this.fixedpanel.HasWindow = false;
			this.eventbox.Add (this.fixedpanel);
			this.Add (this.eventbox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.eventbox.EnterNotifyEvent += new global::Gtk.EnterNotifyEventHandler (this.EventBox_EnterNotifyEvent);
			this.eventbox.LeaveNotifyEvent += new global::Gtk.LeaveNotifyEventHandler (this.EventBox_LeaveNotifyEvent);
			this.eventbox.MotionNotifyEvent += new global::Gtk.MotionNotifyEventHandler (this.EventBox_MotionNotifyEvent);
		}
	}
}
