
// This file has been generated by the GUI designer. Do not modify.
namespace GFCDock
{
	internal partial class DockAutoHideWindow
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GFCDock.DockAutoHideWindow
			this.CanFocus = true;
			this.Events = ((global::Gdk.EventMask)(8196));
			this.Name = "GFCDock.DockAutoHideWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("DockAutoHideWindow");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(2));
			this.Modal = true;
			this.BorderWidth = ((uint)(1));
			this.Resizable = false;
			this.AllowGrow = false;
			this.Decorated = false;
			this.DestroyWithParent = true;
			this.SkipPagerHint = true;
			this.SkipTaskbarHint = true;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
