
// This file has been generated by the GUI designer. Do not modify.
namespace GFCDock
{
	internal partial class DockCaption
	{
		private global::Gtk.EventBox eventbox;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GFCDock.DockCaption
			global::Stetic.BinContainer.Attach (this);
			this.CanFocus = true;
			this.Name = "GFCDock.DockCaption";
			// Container child GFCDock.DockCaption.Gtk.Container+ContainerChild
			this.eventbox = new global::Gtk.EventBox ();
			this.eventbox.Events = ((global::Gdk.EventMask)(13060));
			this.eventbox.Name = "eventbox";
			this.eventbox.VisibleWindow = false;
			this.Add (this.eventbox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.eventbox.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.EventBox_ButtonPressEvent);
			this.eventbox.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.EventBox_ButtonReleaseEvent);
			this.eventbox.EnterNotifyEvent += new global::Gtk.EnterNotifyEventHandler (this.EventBox_EnterNotifyEvent);
			this.eventbox.LeaveNotifyEvent += new global::Gtk.LeaveNotifyEventHandler (this.EventBox_LeaveNotifyEvent);
			this.eventbox.MotionNotifyEvent += new global::Gtk.MotionNotifyEventHandler (this.EventBox_MotionNotifyEvent);
		}
	}
}
