
// This file has been generated by the GUI designer. Do not modify.
namespace GFCDockSample
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action HelpAction;

		private global::Gtk.Action cancelAction;

		private global::Gtk.Action DockPanelAction;

		private global::Gtk.Action ClearAction;

		private global::Gtk.Action SaveCurrentPerpsectiveAction;

		private global::Gtk.Action ThemeHelperAction;

		private global::Gtk.VBox vbox1;

		private global::Gtk.MenuBar menubar2;

		private global::Gtk.HBox hbox2;

		private global::GFCDock.DockPerspective dockperspective;

		private global::Gtk.HButtonBox hbuttonbox3;

		private global::Gtk.Button Left;

		private global::Gtk.Button Right;

		private global::Gtk.Button Top;

		private global::Gtk.Button bottom;

		private global::Gtk.Button Document;

		private global::GFCDock.DockPanel dockPanel;

		private global::Gtk.Statusbar statusbar1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GFCDockSample.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
			this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
			w1.Add (this.HelpAction, null);
			this.cancelAction = new global::Gtk.Action ("cancelAction", null, null, "gtk-cancel");
			w1.Add (this.cancelAction, null);
			this.DockPanelAction = new global::Gtk.Action ("DockPanelAction", global::Mono.Unix.Catalog.GetString ("DockPanel"), null, null);
			this.DockPanelAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("DockPanel");
			w1.Add (this.DockPanelAction, null);
			this.ClearAction = new global::Gtk.Action ("ClearAction", global::Mono.Unix.Catalog.GetString ("Clear"), null, null);
			this.ClearAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Clear");
			w1.Add (this.ClearAction, null);
			this.SaveCurrentPerpsectiveAction = new global::Gtk.Action ("SaveCurrentPerpsectiveAction", global::Mono.Unix.Catalog.GetString ("Save current perpsective"), null, null);
			this.SaveCurrentPerpsectiveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Serialize");
			w1.Add (this.SaveCurrentPerpsectiveAction, null);
			this.ThemeHelperAction = new global::Gtk.Action ("ThemeHelperAction", global::Mono.Unix.Catalog.GetString ("Theme Helper"), null, null);
			this.ThemeHelperAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Theme Helper");
			w1.Add (this.ThemeHelperAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "GFCDockSample.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Role = "";
			// Container child GFCDockSample.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar2'><menu name='DockPanelAction' action='DockPanelAction'><menuitem name='ClearAction' action='ClearAction'/><menuitem name='SaveCurrentPerpsectiveAction' action='SaveCurrentPerpsectiveAction'/><separator/><menuitem name='ThemeHelperAction' action='ThemeHelperAction'/></menu></menubar></ui>");
			this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar2")));
			this.menubar2.Name = "menubar2";
			this.vbox1.Add (this.menubar2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.dockperspective = new global::GFCDock.DockPerspective ();
			this.dockperspective.Events = ((global::Gdk.EventMask)(256));
			this.dockperspective.Name = "dockperspective";
			this.hbox2.Add (this.dockperspective);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.dockperspective]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.hbuttonbox3 = new global::Gtk.HButtonBox ();
			this.hbuttonbox3.Name = "hbuttonbox3";
			this.hbuttonbox3.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
			this.Left = new global::Gtk.Button ();
			this.Left.CanFocus = true;
			this.Left.Name = "Left";
			this.Left.UseUnderline = true;
			this.Left.Label = global::Mono.Unix.Catalog.GetString ("Left");
			this.hbuttonbox3.Add (this.Left);
			global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3[this.Left]));
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
			this.Right = new global::Gtk.Button ();
			this.Right.CanFocus = true;
			this.Right.Name = "Right";
			this.Right.UseUnderline = true;
			this.Right.Label = global::Mono.Unix.Catalog.GetString ("Right");
			this.hbuttonbox3.Add (this.Right);
			global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3[this.Right]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
			this.Top = new global::Gtk.Button ();
			this.Top.CanFocus = true;
			this.Top.Name = "Top";
			this.Top.UseUnderline = true;
			this.Top.Label = global::Mono.Unix.Catalog.GetString ("Top");
			this.hbuttonbox3.Add (this.Top);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3[this.Top]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
			this.bottom = new global::Gtk.Button ();
			this.bottom.CanFocus = true;
			this.bottom.Name = "bottom";
			this.bottom.UseUnderline = true;
			this.bottom.Label = global::Mono.Unix.Catalog.GetString ("Bottom");
			this.hbuttonbox3.Add (this.bottom);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3[this.bottom]));
			w7.Position = 3;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
			this.Document = new global::Gtk.Button ();
			this.Document.CanFocus = true;
			this.Document.Name = "Document";
			this.Document.UseUnderline = true;
			this.Document.Label = global::Mono.Unix.Catalog.GetString ("Document");
			this.hbuttonbox3.Add (this.Document);
			global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3[this.Document]));
			w8.Position = 4;
			w8.Expand = false;
			w8.Fill = false;
			this.hbox2.Add (this.hbuttonbox3);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.hbuttonbox3]));
			w9.Position = 1;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.dockPanel = new global::GFCDock.DockPanel ();
			this.dockPanel.Name = "dockPanel";
			this.dockPanel.DefaultLeftSize = 200;
			this.dockPanel.DefaultBottomSize = 100;
			this.dockPanel.DefaultRightSize = 100;
			this.dockPanel.DefaultTopSize = 200;
			this.vbox1.Add (this.dockPanel);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.dockPanel]));
			w11.Position = 2;
			// Container child vbox1.Gtk.Box+BoxChild
			this.statusbar1 = new global::Gtk.Statusbar ();
			this.statusbar1.Name = "statusbar1";
			this.statusbar1.Spacing = 6;
			this.vbox1.Add (this.statusbar1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.statusbar1]));
			w12.PackType = ((global::Gtk.PackType)(1));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 625;
			this.DefaultHeight = 576;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.MainWindow_DeleteEvent);
			this.ClearAction.Activated += new global::System.EventHandler (this.Clear_Activated);
			this.SaveCurrentPerpsectiveAction.Activated += new global::System.EventHandler (this.Serialize_Activated);
			this.ThemeHelperAction.Activated += new global::System.EventHandler (this.ThemeHelper_Activated);
			this.Left.Clicked += new global::System.EventHandler (this.Left_Clicked);
			this.Right.Clicked += new global::System.EventHandler (this.Right_Clicked);
			this.Top.Clicked += new global::System.EventHandler (this.Top_Clicked);
			this.bottom.Clicked += new global::System.EventHandler (this.Bottom_Clicked);
			this.Document.Clicked += new global::System.EventHandler (this.Document_Clicked);
		}
	}
}
